#!/bin/sh
# install.sh - STAS command installation (macOS / Linux)
# ------------------------------------------------------------------
#   1. checks Node.js            -> aborts cleanly if missing
#   2. checks the version        -> Node >= 18 required
#   3. installs the "stas" command (unix twin of STAS.bat) into a
#      PATH folder: /usr/local/bin if writable, else ~/.local/bin
#   4. validates with the test suite
#
# Usage: after cloning, from this folder:
#   ./install.sh
set -u

ROOT=$(cd "$(dirname "$0")" && pwd)

echo
echo "=== STAS - installation ==="
echo

# --- Windows? REFUSE ------------------------------------------------------
# On Windows (git-bash/MSYS/Cygwin), this script would drop an
# extensionless 'stas' wrapper in ~/.local/bin: PowerShell/cmd would
# try to open it with an external app ("choose an app" dialog)
# instead of running STAS.bat. The right installer there is install.bat.
case "$(uname -s)" in
  MINGW*|MSYS*|CYGWIN*|Windows_NT)
    echo "[ERROR] This machine is running Windows - use install.bat."
    echo ""
    echo "        (install.sh would drop an extensionless 'stas' file"
    echo "        there, breaking the command in PowerShell/cmd.)"
    exit 1 ;;
esac

# --- 0. launched from the project root? ------------------------------------
if [ ! -f "$ROOT/package.json" ]; then
  echo "[ERROR] package.json not found - run install.sh from the root"
  echo "        of the cloned STAS folder."
  exit 1
fi

# --- 1. Node.js present? -----------------------------------------------------
if ! command -v node >/dev/null 2>&1; then
  echo "[ERROR] Node.js is not installed."
  echo
  echo "        Install it (version 18 or newer):"
  echo "          https://nodejs.org   or   brew install node"
  echo "        then run ./install.sh again"
  exit 1
fi

# --- 2. Version >= 18? ---------------------------------------------------------
NODEV=$(node --version)
MAJOR=${NODEV#v}
MAJOR=${MAJOR%%.*}
echo "[ok] Node.js $NODEV detected"
if ! [ "$MAJOR" -ge 18 ] 2>/dev/null; then
  echo "[ERROR] Node.js 18 or newer is required - you have $NODEV."
  echo "        Update Node then run ./install.sh again"
  exit 1
fi

# --- 3. stas command --------------------------------------------------------------
# The wrapper mirrors STAS.bat: serve / test / --web / run verb /
# examples: prefix remap
BIN=""
for d in /usr/local/bin "$HOME/.local/bin"; do
  if [ -d "$d" ] && [ -w "$d" ]; then BIN="$d"; break; fi
done
if [ -z "$BIN" ]; then
  if mkdir -p "$HOME/.local/bin" 2>/dev/null; then
    BIN="$HOME/.local/bin"
  else
    echo "[ERROR] no writable bin folder found"
    echo "        (/usr/local/bin or ~/.local/bin) - permissions?"
    exit 1
  fi
fi

cat > "$BIN/stas" <<EOF
#!/bin/sh
# stas - command generated by install.sh (root: $ROOT)
# Unix twin of STAS.bat: same dispatch, same arguments.
R="$ROOT"
case "\$1" in
  help|-h|--help)
    cat <<'USAGE'
stas - STOS ASCII System

  stas                              interactive STAS> console
  stas <file.bas|examples:name>     run a program
  stas run <file.bas|examples:name>
  stas --edit <file.bas>            edit in the console
  stas --web [--edit <file.bas>]    server + browser
  stas serve                        web server only
  stas test                         tests
  stas help                         this help
USAGE
    exit 0 ;;
  serve) exec node "\$R/packages/stas-web/serve.js" ;;
  test)  cd "\$R" && exec node --test test/ ;;
esac
for a in "\$@"; do
  if [ "\$a" = "--web" ]; then exec node "\$R/packages/stas-web/bin/launch.js" "\$@"; fi
done
[ "\$1" = "run" ] && shift
# remap examples:xxx -> examples folder of this installation.
# POSIX idiom without arrays: counted rotation - each argument passes
# once at the front (processed), then joins the queue; n rounds =
# list remapped in order. (A plain while + set -- "\$@" would loop
# forever: the same element would be reprocessed endlessly.)
n=\$#
i=0
while [ \$i -lt \$n ]; do
  a=\$1; shift
  case \$a in examples:*) a="\$R/examples/\${a#examples:}" ;; esac
  set -- "\$@" "\$a"
  i=\$((i+1))
done
exec node "\$R/packages/stas-console/bin/stas.js" "\$@"
EOF
chmod +x "$BIN/stas"
echo "[ok] stas command installed -> $BIN/stas"

# Cleanup: an old wrapper (moved or copied installation)?
# The wrapper embeds its root (R="...") - if it points elsewhere:
#  - root gone     -> delete it (broken command)
#  - root alive    -> warn (two installations coexist, the first
#    one in the PATH wins)
for d in /usr/local/bin "$HOME/.local/bin"; do
  [ "$d" = "$BIN" ] && continue
  f="$d/stas"
  [ -f "$f" ] || continue
  old=$(sed -n 's/^R="\(.*\)"$/\1/p' "$f" 2>/dev/null)
  [ -n "$old" ] && [ "$old" != "$ROOT" ] || continue
  if [ -d "$old" ]; then
    echo "[!] another stas wrapper exists ($f) pointing to $old"
    echo "    two installations coexist - delete the unneeded one."
  else
    rm -f "$f"
    echo "[cleanup] old wrapper deleted: $f (root gone: $old)"
  fi
done

# ~/.local/bin not in the PATH? say so
if [ "$BIN" = "$HOME/.local/bin" ]; then
  case ":$PATH:" in
    *":$BIN:"*) ;;
    *)
      echo "[!] $BIN is not in your PATH - add this line"
      echo "    to ~/.zshrc or ~/.bashrc:"
      echo "      export PATH=\"\$HOME/.local/bin:\$PATH\""
      ;;
  esac
fi

# --- 4. Validation tests -------------------------------------------------------
echo
echo "=== Validation tests ==="
cd "$ROOT"
LOG=$(mktemp)
if node --test test/ > "$LOG" 2>&1; then
  grep -E '^# (tests|pass|fail)' "$LOG"
  echo "[ok] test suite is green"
else
  grep -E '^# (tests|pass|fail)|^not ok' "$LOG" | head -20
  echo "[warning] some tests failed - see above."
fi
rm -f "$LOG"

# --- End ----------------------------------------------------------------------------
echo
echo "=== Installation complete ==="
echo
echo "Open a NEW terminal, then:"
echo
echo "  stas                        interactive STAS> console"
echo "  stas examples:hello.bas     run a demo"
echo "  stas run mygame.bas         run a program"
echo "  stas --edit mygame.bas      edit in the console"
echo "  stas --web                  server + browser"
echo "  stas serve                  web server only"
echo "  stas help                   full help"
echo
